# Support/Gemfile
source 'https://rubygems.org'
ruby '3.1.7'

# Core dependencies
gem 'sinatra', '~> 3.0'
gem 'faye-websocket', '~> 0.11.0'
gem 'thin', '~> 1.8'

# AI client and helpers
gem 'faraday', '~> 2.8'

# Optional: memory store
gem 'sqlite3', '~> 1.5'

gem 'yaml'

gem 'redcarpet', '~> 3.6'

gem "rouge", "~> 4.6"

gem "ruby-enum", "~> 1.0"

gem "rspec", "~> 3.13"

gem "textpow", "~> 1.4"

gem "differ", "~> 0.1.2"

gem "tiktoken_ruby", "~> 0.0.9"

gem "diffy", "~> 3.4"

gem "htmldiff", git: "https://github.com/myobie/htmldiff.git"

gem "dotenv", "~> 3.1"

gem "dotenvx", "~> 0.0.2"

gem "concurrent-ruby", "~> 1.3"
